### ISSUE TITLE
Cannot npm install beamcoder on windows

### ISSUE THREAD

**Issue by heleon19** [Streampunk/beamcoder#69]
Hi

I get following error, looks like the ffmpeg version 4.3 is not available any more.

$ npm install beamcoder

> beamcoder@0.6.10 preinstall C:\DATEN\nodejs\beamcode\node_modules\beamcoder
> node install_ffmpeg.js

Checking/Installing FFmpeg dependencies for Beam Coder on Windows.
Downloaded 100% of 'latest autobuilds'. Total length 82032 bytes.
TypeError [ERR_INVALID_URL]: Invalid URL: <p><a href="
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at request (https.js:283:30)
    at Object.get (https.js:314:15)
    at C:\DATEN\nodejs\beamcode\node_modules\beamcoder\install_ffmpeg.js:34:11
    at new Promise (<anonymous>)
    at get (C:\DATEN\nodejs\beamcode\node_modules\beamcoder\install_ffmpeg.js:33:10)
    at C:\DATEN\nodejs\beamcode\node_modules\beamcoder\install_ffmpeg.js:116:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async win32 (C:\DATEN\nodejs\beamcode\node_modules\beamcoder\install_ffmpeg.js:104:3) {
  input: '<p><a href="',
  code: 'ERR_INVALID_URL'
}
(node:73828) UnhandledPromiseRejectionWarning: Error: FILE_ENDED
    at PullStream.pull (C:\DATEN\nodejs\beamcode\node_modules\beamcoder\node_modules\unzipper\lib\PullStream.js:83:28)
    at PullStream.emit (events.js:321:20)
    at PullStream.<anonymous> (C:\DATEN\nodejs\beamcode\node_modules\beamcoder\node_modules\unzipper\lib\PullStream.js:20:10)
    at PullStream.emit (events.js:333:22)
    at finishMaybe (_stream_writable.js:698:14)
    at endWritable (_stream_writable.js:715:3)
    at PullStream.Writable.end (_stream_writable.js:635:5)
    at ReadStream.onend (_stream_readable.js:673:10)
    at Object.onceWrapper (events.js:427:28)
    at ReadStream.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:73828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:73828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sparkpunkd** [comment]
Noticed the same here. Just fixed it ... although we'll have to look into making this less brittle-in-change for the future.

**Comment by heleon19** [comment]
Ok, now it works, thank you
